---
# header name = header_name.upper() + "_CONFIG.h", if "header_name" not defined or left blank, use yaml file name + "_CONFIG.h"
header_name: 

pitch:
  offset: 4.725
  max: 0.408
  proximity: 0.136 # 0.408 / 3
  move:
    kp: 1400
    ki: 0
    kd: 2200
  hold:
    kp: 3200
    ki: 100
    kd: 3100

yaw:
  offset: 3.406
  max: 1.551
  proximity: 0.517 # 1.551 / 3
  move:
    kp: 1000
    ki: 0
    kd: 200
  hold:
    kp: 3000
    ki: 60
    kd: 2500

