name: arm build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
    # cached ARM toolchain
    - name: cache ARM toolchain
      id: cache-arm
      uses: actions/cache@v2
      with:
        path: ~/arm-toolchain-v10-3
        key: ${{ runner.os }}-arm-toolchain
    # download ARM toolchain
    - name: download ARM toolchain
      if: steps.cache-arm.outputs.cache-hit != 'true'
      run: |
        wget -O ~/gcc-arm-none-eabi.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
        mkdir ~/arm-toolchain-v10-3
        tar -xjf ~/gcc-arm-none-eabi.tar.bz2 --directory ~/arm-toolchain-v10-3 --strip-components=1
    - name: add system path
      run: echo "~/arm-toolchain-v10-3/bin" >> $GITHUB_PATH  # set envrionment variable
    - name: cmake
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
    # format check temporarily commented
    - name: format check
      run: make check-format
      working-directory: build
    - name: build
      run: make -j
      working-directory: build
